spring:
  application:
    name: FOOTBALLER-SERVICE

server:
  port: 8081

management:
  security:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
       enabled: true

