eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
       enabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27081
      database: footballer_db
