version: "3"

services:

  registry-service:
    image: registry-service
    ports:
      - "8761:8761"
    networks:
      - webnet

  gateway-service:
    image: gateway-service
    ports:
      - "9090:9090"
    depends_on:
      - registry-service
    networks:
      - webnet

  footballer-service:
    image: footballer-service
    ports:
      - "8081"
    depends_on:
      - registry-service
      - footballer-db
    networks:
      - webnet

  team-service:
    image: team-service
    ports:
      - "8082"
    depends_on:
      - registry-service
      - team-db
    networks:
      - webnet

  footballer-db:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "footballer-db-data:/data/db"
    ports:
      - "27081:27017"
    networks:
      - webnet

  team-db:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "team-db-data:/data/db"
    ports:
      - "27082:27017"
    networks:
      - webnet


networks:
  webnet:

volumes:
  footballer-db-data:
    external: true
  team-db-data:
    external: true