version: "3"

services:

  registry-service:
    image: registry-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8761:8761"
    networks:
      - webnet

  gateway-service:
    image: gateway-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - registry-service
    networks:
      - webnet

  footballer-service:
    image: footballer-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - registry-service
    networks:
      - webnet

  team-service:
    image: team-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - registry-service
    networks:
      - webnet


networks:
  webnet: