spring:
  application:
    name: GATEWAY-SERVICE
  profiles:
    active: docker

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eureka:
    enabled: true

server:
  port: 9090

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    footballer-service-route:
      path: /footballer/**
      serviceId: FOOTBALLER-SERVICE
      stripPrefix: false
    team-service-route:
      path: /team/**
      serviceId: TEAM-SERVICE
      stripPrefix: false

