version: "3"

services:

  mongodb:
    image: mongo
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "db-data:/data/db"
    ports:
      - "27017:27017"
    networks:
      - webnet


networks:
  webnet:

volumes:
  db-data: