version: "3"

services:

  mongodb-local-footballer:
    image: mongo
    deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "footballer-db-data:/data/db"
    ports:
      - "27081:27017"
    networks:
      - webnet

networks:
  webnet:

volumes:
  footballer-db-data:
    external: true