spring:
  application:
    name: TEAM-SERVICE
  profiles:
    active: local

server:
  port: 8082

management:
  security:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
       enabled: true